spring:
  application:
    name: videochat
  thymeleaf:
    cache: false
  web:
    resources:
      static-locations:
        - classpath:/static/
        - classpath:/public/
        - classpath:/resources/
        - classpath:/META-INF/resources/
server:
  port: 9443
  address: 0.0.0.0
  ssl:
    key-store: "classpath:keystore.p12"
    key-store-password: "000000"
    key-store-type: PKCS12
